### ISSUE TITLE
Error after Platformio-Espressif32 core update 1.6.0

### ISSUE THREAD

**Issue by MkLHX** [vincasmiliunas/ESP32-Arduino-TB6612FNG#2]
Hi there!

I'm working on a project based on ESP32 who use the TB6612FNG lib.

After i updated the espressif32 core to 1.6.0 through platformio i get this error 
```
Compiling .pioenvs\esp32dev\FrameworkArduino\esp32-hal-bt.c.o*** [.pioenvs\esp32dev\libe91\ESP32-Arduino-TB6612FNG-master\TB6612FNG.cpp.o] Error 1
``` 
So i'm going to TB6612FNG.cpp file and see theses errors :
```
no instance of overloaded function "max" matches the argument list -- argument types are: (double, <error-type>)
max
```

```
no instance of overloaded function "min" matches the argument list -- argument types are: (double, float)
min
```

On this code part : 

https://github.com/vincasmiliunas/ESP32-Arduino-TB6612FNG/blob/master/TB6612FNG.cpp#L19

So what we can do to fix it?

Thx

**Comment by vincasmiliunas** [comment]
Hi,

thanks for spotting this.

Looks like previously the C min and max functions were defined somewhere by Arduino.h and currently those definitions are gone or no longer leaking out.

I've updated the code to use the C++ versions, it compiles, so should be working.

Thanks!

**Comment by MkLHX** [comment]
It's works !! 

Thx for the speedest response and bugfix ever seen on github!
